version: '3.3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: fattybobcat/foodgram:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - ./.env 
     
  nginx:
    image: nginx:1.19.7
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "80:80"
    depends_on:
      - web
